services:
  rc-automation:
    build: .
    volumes:
      - .:/app
      - ./RC/logs:/app/RC/logs
    env_file:
      - .env
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - RC_E_1=${RC_E_1}
      - RC_P_1=${RC_P_1}
      - RC_E_2=${RC_E_2}
      - RC_P_2=${RC_P_2}
    # Remove the default command to allow passing arguments
    # command: /app/RC/shell.sh 