version: '3.8'

services:
  rc-automation:
    build: .
    volumes:
      - .:/app
      - ./RC/logs:/app/RC/logs
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    command: >
      bash -c "
        if [ ! -f RC/.env ]; then
          infisical export --env=prod --format=dotenv > RC/.env
        fi
        python RC/rc_a.py
      " 